path: C:/Users/choy/Downloads/Archive/data
train: train/images
val: val/images
test: test/images

# Classes
names:
    0: bread
    1: pasta
    2: rice
    3: apple
    4: banana
    5: bellpepper
    6: broccoli
    7: chicken
    8: fish
